#include "kettlingur.h"

//upper micro
static inline void ABS(reg32 opcode){}
static inline void ADD(reg32 opcode){}
static inline void ADDi(reg32 opcode){}
static inline void ADDq(reg32 opcode){}
static inline void ADDbc(reg32 opcode){}
static inline void ADDA(reg32 opcode){}
static inline void ADDAi(reg32 opcode){}
static inline void ADDAq(reg32 opcode){}
static inline void ADDAbc(reg32 opcode){}
static inline void CLIP(reg32 opcode){}
static inline void FTOI0(reg32 opcode){}
static inline void FTOI4(reg32 opcode){}
static inline void FTOI12(reg32 opcode){}
static inline void FTOI15(reg32 opcode){}
static inline void ITOF0(reg32 opcode){}
static inline void ITOF4(reg32 opcode){}
static inline void ITOF12(reg32 opcode){}
static inline void ITOF15(reg32 opcode){}
static inline void MADD(reg32 opcode){}
static inline void MADDi(reg32 opcode){}
static inline void MADDq(reg32 opcode){}
static inline void MADDbc(reg32 opcode){}
static inline void MADDA(reg32 opcode){}
static inline void MADDAi(reg32 opcode){}
static inline void MADDAq(reg32 opcode){}
static inline void MADDAbc(reg32 opcode){}
static inline void MAX(reg32 opcode){}
static inline void MAXi(reg32 opcode){}
static inline void MAXbc(reg32 opcode){}
static inline void MIN(reg32 opcode){}
static inline void MINi(reg32 opcode){}
static inline void MINbc(reg32 opcode){}
static inline void MSUB(reg32 opcode){}
static inline void MSUBi(reg32 opcode){}
static inline void MSUBq(reg32 opcode){}
static inline void MSUBbc(reg32 opcode){}
static inline void MSUBA(reg32 opcode){}
static inline void MSUBAi(reg32 opcode){}
static inline void MSUBAq(reg32 opcode){}
static inline void MSUBAbc(reg32 opcode){}
static inline void MUL(reg32 opcode){}
static inline void MULi(reg32 opcode){}
static inline void MULq(reg32 opcode){}
static inline void MULbc(reg32 opcode){}
static inline void MULA(reg32 opcode){}
static inline void MULAi(reg32 opcode){}
static inline void MULAq(reg32 opcode){}
static inline void MULAbc(reg32 opcode){}
static inline void NOP(reg32 opcode){}
static inline void OPMULA(reg32 opcode){}
static inline void OPMSUB(reg32 opcode){}
static inline void SUB(reg32 opcode){}
static inline void SUBi(reg32 opcode){}
static inline void SUBq(reg32 opcode){}
static inline void SUBbc(reg32 opcode){}
static inline void SUBA(reg32 opcode){}
static inline void SUBAi(reg32 opcode){}
static inline void SUBAq(reg32 opcode){}
static inline void SUBAbc(reg32 opcode){}
//lower micro
static inline void B(reg32 opcode){}
static inline void BAL(reg32 opcode){}
static inline void DIV(reg32 opcode){}
static inline void EATAN(reg32 opcode){}
static inline void EATANxy(reg32 opcode){}
static inline void EATANxz(reg32 opcode){}
static inline void EEXP(reg32 opcode){}
static inline void ELENG(reg32 opcode){}
static inline void ERCPR(reg32 opcode){}
static inline void ERLENG(reg32 opcode){}
static inline void ERSADD(reg32 opcode){}
static inline void ESIN(reg32 opcode){}
static inline void ESQRT(reg32 opcode){}
static inline void ESUM(reg32 opcode){}
static inline void FCAND(reg32 opcode){}
static inline void FCEQ(reg32 opcode){}
static inline void FCGET(reg32 opcode){}
static inline void FCOR(reg32 opcode){}
static inline void FCSET(reg32 opcode){}
static inline void FMAND(reg32 opcode){}
static inline void FMEQ(reg32 opcode){}
static inline void FMOR(reg32 opcode){}
static inline void FSAND(reg32 opcode){}
static inline void FSEQ(reg32 opcode){}
static inline void FSOR(reg32 opcode){}
static inline void FSSET(reg32 opcode){}
static inline void IADD(reg32 opcode){}
static inline void IADDI(reg32 opcode){}
static inline void IADDIU(reg32 opcode){}

static inline void IAND(reg32 opcode){}
static inline void IBEQ(reg32 opcode){}
static inline void IBGEZ(reg32 opcode){}
static inline void IBGTZ(reg32 opcode){}
static inline void IBLEZ(reg32 opcode){}
static inline void IBLTZ(reg32 opcode){}
static inline void IBNE(reg32 opcode){}
static inline void ILW(reg32 opcode){}
static inline void ILWR(reg32 opcode){}
static inline void IOR(reg32 opcode){}
static inline void ISUB(reg32 opcode){}
static inline void ISUBIU(reg32 opcode){}
static inline void ISW(reg32 opcode){}
static inline void ISWR(reg32 opcode){}
static inline void JR(reg32 opcode){}
static inline void LQ(reg32 opcode){}
static inline void LQD(reg32 opcode){}
static inline void LDI(reg32 opcode){}
static inline void MFIR(reg32 opcode){}
static inline void MFP(reg32 opcode){}
static inline void MOVE(reg32 opcode){}
static inline void MR32(reg32 opcode){}
static inline void MTIR(reg32 opcode){}
static inline void RGET(reg32 opcode){}
static inline void RINIT(reg32 opcode){}
static inline void RNEXT(reg32 opcode){}
static inline void RSQRT(reg32 opcode){}
static inline void RXOR(reg32 opcode){}
static inline void SQ(reg32 opcode){}
static inline void SQD(reg32 opcode){}
static inline void SQI(reg32 opcode){}
static inline void SQRT(reg32 opcode){}

static inline void WAITP(reg32 opcode){}
static inline void WAITQ(reg32 opcode){}
static inline void XGKICK(reg32 opcode){}
static inline void XITOP(reg32 opcode){}
static inline void XTOP(reg32 opcode){}